title: OpenSpending Extension Proposals
author: Open Knowledge Labs
authorurl: http://okfnlabs.org/
github: http://github.com/openspending/osep/
mailinglist: http://lists.okfn.org/mailman/listinfo/openspending-dev
twitter: OpenSpending
